Improve Dropbox daemon start logic.

diff --git a/private_dot_bashrc.tmpl b/private_dot_bashrc.tmpl
--- a/private_dot_bashrc.tmpl
+++ b/private_dot_bashrc.tmpl
@@ -251,17 +251,18 @@ fi
 #########################################################################################################################
 
 # The 'dropbox' script is created by fresh install in '~/.local/bin"
-if which dropbox >/dev/null ; then
-    status=$(dropbox status)
+if ! pgrep dropbox >/dev/null ; then
 
-    if [ "${status}" == "Dropbox isn't running!" ] ; then
-        dropbox start
-    elif [ "${status}" != "Up to date" ] ; then
-        echo "Failed to start Dropbox!"
-        # TODO: Find a clean way to notify and log
-        #       see https://wiki.archlinux.org/title/Desktop_notifications
+    if [ ! -d ~/.dropbox-dist ] ; then
+      echo "Dropbox install not found!"
+      echo "see https://www.dropbox.com/install-linux"
+      # TODO: Find a clean way to notify and log
+      #       see https://wiki.archlinux.org/title/Desktop_notifications
+    else
+      ~/.dropbox-dist/dropboxd > /tmp/dropboxd.log 2>&1 &
     fi
 fi
+
 {{- end }}
 
 
